### ISSUE TITLE
Naming convention on login function: "sarufi.log()"

### ISSUE THREAD

**Issue by maen08** [flexcodelabs/sarufi#13]
Hello, great work team, appreciate ! 

Its not a feature but rather, convention in naming a login function. I would suggest to rename `sarufi.log()` into `sarufi.login()` 
This is because "log" itself can mean something different and may confuse amateur developer.
Confusion can come from, for example:  "console.log()"  or "log" as from "logs" - "the file of system events"

Great work!

@BaharaJr @neicore

**Comment by BaharaJr** [comment]
Hello, @maen08 thank you for the feedback, that was actually a typo in the docs, the actual method is 
```JS 
sarufi.login() 

```

**Comment by maen08** [comment]
Okay, I did have time to go through the code. Great work @BaharaJr

**Comment by BaharaJr** [comment]
> Okay, I did have time to go through the code. Great work @BaharaJr

We will appreciate you going through the docs and pointing this out @maen08. The docs have been updated.

**Comment by maen08** [comment]
Sure, i will
